export const GET_HOME_MENU_LIST = 'GET_HOME_MENU_LIST'
export const GET_HOME_MENU_LIST_SUCCESS = 'GET_HOME_MENU_LIST_SUCCESS'
export const GET_HOME_MENU_LIST_FAILURE = 'GET_HOME_MENU_LIST_FAILURE'
export const RESET_HOME_MENU_LIST = 'RESET_HOME_MENU_LIST'
